### ISSUE TITLE
Not able to send data to kount

### ISSUE THREAD

**Issue by mwaqassatti** [Kount/kount-android-sdk#8]
I am using count sdk version 3.2 but i got to know from kount that they got no data from device. I follow the checkout example from sdk. I write this method below the location permission is already ON. The callback method 'completed' is also called. Can you please help me what is missing.

private void initKount() {

        final DataCollector dataCollector = DataCollector.getInstance();
        dataCollector.setDebug(true);
        dataCollector.setContext(this);
        dataCollector.setEnvironment(DataCollector.ENVIRONMENT_TEST);
        dataCollector.setMerchantID(Constants.MERCHANT_ID);
        dataCollector.setLocationCollectorConfig(DataCollector.LocationConfig.COLLECT);
        String sessionID = UUID.randomUUID().toString();
        final String deviceSessionID = sessionID.replace("-", "");
        new Handler(Looper.getMainLooper()).post(new Runnable() {
            public void run() {
                dataCollector.collectForSession(deviceSessionID, new com.kount.api.DataCollector.CompletionHandler() {
                    @Override
                    public void completed(String s) {
                        Log.e("success",""+s);
                    }

                    @Override
                    public void failed(String s, final DataCollector.Error error) {
                    }

                });
            }
        });
    }

**Comment by mwaqassatti** [comment]
Any help on this would be really appreciated.

**Comment by gjd-keynetics** [comment]
The Data Collector gathers data and sends it back to our servers. You cannot access it directly in the Data Collector SDK as it has not been processed yet. In order to see or use the information you need to call one of our API endpoints (for either Kount Access or Kount Complete).  You will use the sessionID that you provide in the Data collector as the identifier in the API call to retrieve the information (in addition to your merchantID). These are generally done by you sending your session_id back to your servers and then making server to server calls from yours to Kount's.  We don't allow Mobile devices to directly call our API endpoints because it could allow a fraudster to setup a man-in-the-middle attack and circumvent your attempts to prevent fraud.

For example, if you are using our **Kount Access** (login fraud detection and device information) product and your servers are running Node.js, then you would want to use our [node.js sdk](https://github.com/Kount/kount-access-nodejs-sdk) passing in your merchantID, sessionID, and API key to get either device, login velocity, or decision information.  
If you are using .Net with **Kount Complete** service to make a decision on a financial transaction you should use our [.Net RIS SDK](https://github.com/Kount/kount-ris-dotnet-sdk) and also submit information around the order you want to evaluate (like what's in the shopping cart, billing/shipping addresses, payment methods, etc).

Hopefully that gets you going in the right direction.

**Comment by mwaqassatti** [comment]
@gjd-keynetics  Thanks
